(in-package #:yaml-protocol)

;;; YAML 1.2 emitter. :json style is valid YAML (JSON schema). :block uses
;;; indent mappings/sequences. Same Lisp mapping as json-protocol.

(defun %safe-plain-p (s)
  (and (plusp (length s))
       (not (find-if (lambda (c)
                       (or (char= c #\Newline) (char= c #\Return)
                           (char= c #\:) (char= c #\#) (char= c #\&)
                           (char= c #\*) (char= c #\!) (char= c #\|)
                           (char= c #\>) (char= c #\') (char= c #\")
                           (char= c #\{) (char= c #\}) (char= c #\[)
                           (char= c #\]) (char= c #\,)))
                     s))
       (not (space-p (char s 0)))
       (not (space-p (char s (1- (length s)))))
       (let ((resolved (resolve-plain s)))
         (stringp resolved))))

(defun %emit-quoted (s stream)
  (write-char #\" stream)
  (loop for c across s
        do (case c
             (#\" (write-string "\\\"" stream))
             (#\\ (write-string "\\\\" stream))
             (#\Newline (write-string "\\n" stream))
             (#\Return (write-string "\\r" stream))
             (#\Tab (write-string "\\t" stream))
             (t (write-char c stream))))
  (write-char #\" stream))

(defun %indent (stream n)
  (dotimes (i n)
    (write-char #\Space stream)))

(defun emit-block (value stream &optional (indent 0) &key (first t))
  (cond
    ((eq value :null)
     (write-string "null" stream))
    ((eq value t)
     (write-string "true" stream))
    ((null value)
     (write-string "false" stream))
    ((stringp value)
     (if (%safe-plain-p value)
         (write-string value stream)
         (%emit-quoted value stream)))
    ((integerp value)
     (princ value stream))
    ((floatp value)
     (let ((*read-default-float-format* 'double-float))
       (princ value stream)))
    ((hash-table-p value)
     (if (zerop (hash-table-count value))
         (write-string "{}" stream)
         (let ((keys (sort (loop for k being the hash-keys of value
                                 collect k)
                           #'string<)))
           (loop for k in keys
                 for i from 0
                 do (unless (and first (zerop i))
                      (write-char #\Newline stream)
                      (%indent stream indent))
                    (if (%safe-plain-p k)
                        (write-string k stream)
                        (%emit-quoted k stream))
                    (write-string ": " stream)
                    (let ((v (gethash k value)))
                      (if (or (and (hash-table-p v) (plusp (hash-table-count v)))
                              (and (vectorp v) (not (stringp v)) (plusp (length v))))
                          (progn
                            (write-char #\Newline stream)
                            (%indent stream (+ indent 2))
                            (emit-block v stream (+ indent 2) :first t))
                          (emit-block v stream (+ indent 2) :first t)))))))
    ((and (vectorp value) (not (stringp value)))
     (if (zerop (length value))
         (write-string "[]" stream)
         (loop for i from 0 below (length value)
               do (unless (and first (zerop i))
                    (write-char #\Newline stream)
                    (%indent stream indent))
                  (write-string "- " stream)
                  (let ((v (aref value i)))
                    (if (or (and (hash-table-p v) (plusp (hash-table-count v)))
                            (and (vectorp v) (not (stringp v)) (plusp (length v))))
                        (emit-block v stream (+ indent 2) :first t)
                        (emit-block v stream (+ indent 2) :first t))))))
    ((and (consp value) (every #'consp value)
          (every (lambda (c) (or (stringp (car c)) (symbolp (car c)))) value))
     (emit-block (%alist-to-ht value) stream indent :first first))
    ((consp value)
     (emit-block (coerce value 'vector) stream indent :first first))
    (t
     (error 'yaml-encode-error
            :message (format nil "cannot encode ~S as YAML" value)))))

(defun %alist-to-ht (alist)
  (let ((ht (make-hash-table :test #'equal)))
    (dolist (pair alist ht)
      (setf (gethash (if (stringp (car pair))
                         (car pair)
                         (string-downcase (string (car pair))))
                     ht)
            (cdr pair)))))

(defun %json-key (k)
  (if (stringp k)
      k
      (string-downcase (string k))))

(defun emit-json (value stream)
  "JSON-schema YAML (flow). Does not need a json-protocol backend."
  (cond
    ((eq value :null)
     (write-string "null" stream))
    ((eq value t)
     (write-string "true" stream))
    ((null value)
     (write-string "false" stream))
    ((stringp value)
     (%emit-quoted value stream))
    ((integerp value)
     (princ value stream))
    ((floatp value)
     (let ((*read-default-float-format* 'double-float))
       (princ value stream)))
    ((hash-table-p value)
     (write-char #\{ stream)
     (let ((keys (sort (loop for k being the hash-keys of value collect k)
                       #'string< :key #'%json-key)))
       (loop for k in keys
             for i from 0
             do (unless (zerop i)
                  (write-char #\, stream))
                (%emit-quoted (%json-key k) stream)
                (write-char #\: stream)
                (emit-json (gethash k value) stream)))
     (write-char #\} stream))
    ((and (vectorp value) (not (stringp value)))
     (write-char #\[ stream)
     (loop for i from 0 below (length value)
           do (unless (zerop i)
                (write-char #\, stream))
              (emit-json (aref value i) stream))
     (write-char #\] stream))
    ((and (consp value) (every #'consp value)
          (every (lambda (c) (or (stringp (car c)) (symbolp (car c)))) value))
     (emit-json (%alist-to-ht value) stream))
    ((consp value)
     (emit-json (coerce value 'vector) stream))
    (t
     (error 'yaml-encode-error
            :message (format nil "cannot encode ~S as YAML" value)))))
