(in-package #:yaml-protocol)

;;; Event stream (yaml-test-suite DSL) + compose.
;;; Parser emits events; compose builds the Lisp graph. Aliases / << / Core
;;; schema are compose-time. :object-class is post-compose (see protocol.lisp).

(defstruct (yaml-event (:constructor make-yaml-event))
  (kind :scalar :type keyword)
  (implicit t)
  (flow-p nil)
  (anchor nil)
  (tag nil)
  (style :plain)
  (value nil))

(defun hex-digit-p (c)
  (and c (or (char<= #\0 c #\9)
             (char<= #\a c #\f)
             (char<= #\A c #\F))))

(defun %core-integer (s)
  (let ((sign 1)
        (start 0)
        (n (length s)))
    (when (zerop n)
      (return-from %core-integer nil))
    (cond
      ((char= (char s 0) #\+) (setf start 1))
      ((char= (char s 0) #\-) (setf start 1 sign -1)))
    (when (>= start n)
      (return-from %core-integer nil))
    (cond
      ((and (>= (- n start) 3)
            (char= (char s start) #\0)
            (or (char= (char s (1+ start)) #\x)
                (char= (char s (1+ start)) #\X)))
       (let ((rest (subseq s (+ start 2))))
         (when (and (plusp (length rest))
                    (every #'hex-digit-p rest))
           (* sign (parse-integer rest :radix 16)))))
      ((and (>= (- n start) 3)
            (char= (char s start) #\0)
            (or (char= (char s (1+ start)) #\o)
                (char= (char s (1+ start)) #\O)))
       (let ((rest (subseq s (+ start 2))))
         (when (and (plusp (length rest))
                    (every (lambda (c) (char<= #\0 c #\7)) rest))
           (* sign (parse-integer rest :radix 8)))))
      ((and (char= (char s start) #\0) (= n (1+ start)))
       0)
      ((and (char<= #\1 (char s start) #\9)
            (every #'digit-char-p (subseq s start)))
       (* sign (parse-integer s :start start)))
      ((and (char= (char s start) #\0)
            (every #'digit-char-p (subseq s start))
            (= n (1+ start)))
       0)
      (t nil))))

(defun %core-float (s)
  (let ((n (length s)))
    (when (zerop n)
      (return-from %core-float nil))
    (flet ((inf-p (x)
             (or (string= x ".inf") (string= x ".Inf") (string= x ".INF")
                 (string= x "+.inf") (string= x "+.Inf") (string= x "+.INF")))
           (ninf-p (x)
             (or (string= x "-.inf") (string= x "-.Inf") (string= x "-.INF")))
           (nan-p (x)
             (or (string= x ".nan") (string= x ".NaN") (string= x ".NAN"))))
      (cond
        ((inf-p s)
         (let ((s (find-symbol "DOUBLE-FLOAT-POSITIVE-INFINITY")))
           (if (and s (boundp s)) (symbol-value s) most-positive-double-float)))
        ((ninf-p s)
         (let ((s (find-symbol "DOUBLE-FLOAT-NEGATIVE-INFINITY")))
           (if (and s (boundp s)) (symbol-value s) most-negative-double-float)))
        ((nan-p s)
         (let ((s (find-symbol "DOUBLE-FLOAT-NAN")))
           (if (and s (boundp s)) (symbol-value s) nil)))
        (t
         (when (and (find-if (lambda (c)
                               (or (char= c #\.) (char= c #\e) (char= c #\E)))
                             s)
                    (every (lambda (c)
                             (or (digit-char-p c)
                                 (member c '(#\+ #\- #\. #\e #\E))))
                           s))
           (let* ((*read-default-float-format* 'double-float)
                  (*read-eval* nil))
             (ignore-errors
               (let ((v (read-from-string s)))
                 (and (numberp v) (float v 1.0d0)))))))))))

(defun resolve-plain (s)
  "YAML 1.2 Core schema on a plain scalar (not 1.1 — NO is a string)."
  (cond
    ((or (string= s "")
         (string= s "~")
         (string= s "null") (string= s "Null") (string= s "NULL"))
     :null)
    ((or (string= s "true") (string= s "True") (string= s "TRUE")) t)
    ((or (string= s "false") (string= s "False") (string= s "FALSE")) nil)
    (t
     (or (%core-integer s)
         (%core-float s)
         s))))

(defun %event-escape (s)
  (with-output-to-string (o)
    (loop for c across s
          do (case c
               (#\\ (write-string "\\\\" o))
               (#\Nul (write-string "\\0" o))
               (#\Backspace (write-string "\\b" o))
               (#\Newline (write-string "\\n" o))
               (#\Return (write-string "\\r" o))
               (#\Tab (write-string "\\t" o))
               (t (write-char c o))))))

(defun %style-char (style)
  (ecase style
    (:plain #\:)
    (:single #\')
    (:double #\")
    (:literal #\|)
    (:folded #\>)))

(defun format-event (event &optional (stream *standard-output*))
  (let ((kind (yaml-event-kind event)))
    (ecase kind
      (:stream-start (write-string "+STR" stream))
      (:stream-end (write-string "-STR" stream))
      (:document-start
       (write-string "+DOC" stream)
       (unless (yaml-event-implicit event)
         (write-string " ---" stream)))
      (:document-end
       (write-string "-DOC" stream)
       (unless (yaml-event-implicit event)
         (write-string " ..." stream)))
      (:mapping-start
       (write-string "+MAP" stream)
       (when (yaml-event-flow-p event)
         (write-string " {}" stream))
       (when (yaml-event-anchor event)
         (format stream " &~A" (yaml-event-anchor event)))
       (when (yaml-event-tag event)
         (format stream " <~A>" (yaml-event-tag event))))
      (:sequence-start
       (write-string "+SEQ" stream)
       (when (yaml-event-flow-p event)
         (write-string " []" stream))
       (when (yaml-event-anchor event)
         (format stream " &~A" (yaml-event-anchor event)))
       (when (yaml-event-tag event)
         (format stream " <~A>" (yaml-event-tag event))))
      (:mapping-end (write-string "-MAP" stream))
      (:sequence-end (write-string "-SEQ" stream))
      (:scalar
       (write-string "=VAL" stream)
       (when (yaml-event-anchor event)
         (format stream " &~A" (yaml-event-anchor event)))
       (when (yaml-event-tag event)
         (format stream " <~A>" (yaml-event-tag event)))
       (write-char #\Space stream)
       (write-char (%style-char (yaml-event-style event)) stream)
       (write-string (%event-escape (or (yaml-event-value event) "")) stream))
      (:alias
       (format stream "=ALI *~A" (yaml-event-value event)))))
  (values))

(defun format-events (events)
  "Render EVENTS as yaml-test-suite test.event text (trailing newline)."
  (with-output-to-string (o)
    (dolist (ev (coerce events 'list))
      (format-event ev o)
      (write-char #\Newline o))))

(defun stringify-key (key)
  (cond
    ((stringp key) key)
    ((eq key :null) "null")
    ((eq key t) "true")
    ((null key) "false")
    ((numberp key) (princ-to-string key))
    (t key)))

(defun merge-mapping (dest src)
  "YAML merge key <<. Existing keys win."
  (cond
    ((hash-table-p src)
     (maphash (lambda (k v)
                (unless (nth-value 1 (gethash k dest))
                  (setf (gethash k dest) v)))
              src))
    ((and (vectorp src) (not (stringp src)))
     (loop for i from (1- (length src)) downto 0
           do (merge-mapping dest (aref src i))))
    (t (error 'yaml-parse-error :message "<< merge value must be a mapping"))))

(defun assign-map-entry (ht key val)
  (let ((k (stringify-key key)))
    (if (and (stringp k) (string= k "<<"))
        (merge-mapping ht val)
        (setf (gethash k ht) val))))

(defun %resolve-scalar (event)
  (let* ((raw (or (yaml-event-value event) ""))
         (tag (yaml-event-tag event))
         (style (yaml-event-style event)))
    (cond
      ((null tag)
       (if (eq style :plain)
           (resolve-plain raw)
           raw))
      ((or (string= tag "!")
           (string= tag "tag:yaml.org,2002:str"))
       (if (and (string= tag "!") (eq style :plain))
           (resolve-plain raw)
           raw))
      ((string= tag "tag:yaml.org,2002:null")
       :null)
      ((string= tag "tag:yaml.org,2002:bool")
       (cond
         ((or (string= raw "true") (string= raw "True") (string= raw "TRUE")) t)
         ((or (string= raw "false") (string= raw "False") (string= raw "FALSE")) nil)
         (t raw)))
      ((string= tag "tag:yaml.org,2002:int")
       (or (%core-integer raw) (ignore-errors (parse-integer raw)) raw))
      ((string= tag "tag:yaml.org,2002:float")
       (or (%core-float raw) raw))
      (t
       (if (eq style :plain)
           (resolve-plain raw)
           raw)))))

(defun compose-events (events &key all)
  "Build Lisp values from an event stream.
   ALL true → vector of documents. Empty stream → :null / #()."
  (let ((vec (coerce events 'vector))
        (i 0)
        (anchors (make-hash-table :test #'equal))
        (docs '()))
    (labels ((peek-kind ()
               (when (< i (length vec))
                 (yaml-event-kind (aref vec i))))
             (next-event ()
               (when (>= i (length vec))
                 (error 'yaml-parse-error :message "unexpected end of event stream"))
               (prog1 (aref vec i)
                 (incf i)))
             (expect (kind)
               (let ((ev (next-event)))
                 (unless (eq (yaml-event-kind ev) kind)
                   (error 'yaml-parse-error
                          :message (format nil "expected ~A got ~A"
                                           kind (yaml-event-kind ev))))
                 ev))
             (compose-node ()
               (let ((ev (next-event)))
                 (ecase (yaml-event-kind ev)
                   (:alias
                    (let ((val (gethash (yaml-event-value ev) anchors :missing)))
                      (when (eq val :missing)
                        (error 'yaml-parse-error
                               :message (format nil "unknown alias *~A"
                                                (yaml-event-value ev))))
                      val))
                   (:scalar
                    (let ((val (%resolve-scalar ev)))
                      (when (yaml-event-anchor ev)
                        (setf (gethash (yaml-event-anchor ev) anchors) val))
                      val))
                   (:sequence-start
                    (let ((items '())
                          (anchor (yaml-event-anchor ev)))
                      (loop until (eq (peek-kind) :sequence-end)
                            do (push (compose-node) items))
                      (expect :sequence-end)
                      (let ((vec (coerce (nreverse items) 'vector)))
                        (when anchor
                          (setf (gethash anchor anchors) vec))
                        vec)))
                   (:mapping-start
                    (let ((ht (make-hash-table :test #'equal))
                          (anchor (yaml-event-anchor ev)))
                      (when anchor
                        (setf (gethash anchor anchors) ht))
                      (loop until (eq (peek-kind) :mapping-end)
                            do (let ((k (compose-node))
                                     (v (compose-node)))
                                 (assign-map-entry ht k v)))
                      (expect :mapping-end)
                      ht))))))
      (expect :stream-start)
      (loop
        (let ((k (peek-kind)))
          (cond
            ((or (null k) (eq k :stream-end))
             (return))
            ((eq k :document-start)
             (next-event)
             (setf anchors (make-hash-table :test #'equal))
             (if (eq (peek-kind) :document-end)
                 (push :null docs)
                 (push (compose-node) docs))
             (expect :document-end))
            (t
             (error 'yaml-parse-error
                    :message (format nil "unexpected event ~A" k))))))
      (when (eq (peek-kind) :stream-end)
        (next-event))
      (let ((docs (nreverse docs)))
        (if all
            (coerce docs 'vector)
            (if docs (first docs) :null))))))
