(in-package #:yaml-protocol)

;;; Native YAML 1.2 event parser. No FFI. Events are the parse product;
;;; compose-events builds Lisp values (see events.lisp).

(defstruct (ys (:constructor %make-ys))
  (text "" :type string)
  (pos 0 :type fixnum)
  (len 0 :type fixnum)
  (events nil)
  (tag-handles nil)
  (parent-indent -1 :type fixnum))

(defun make-ys (text)
  (%make-ys :text text :pos 0 :len (length text)
            :events (make-array 32 :adjustable t :fill-pointer 0)
            :tag-handles (make-hash-table :test #'equal)))

(defun reset-tag-handles (ys)
  (let ((ht (ys-tag-handles ys)))
    (clrhash ht)
    (setf (gethash "!" ht) "!"
          (gethash "!!" ht) "tag:yaml.org,2002:")))

(defun ys-eof-p (ys)
  (>= (ys-pos ys) (ys-len ys)))

(defun ys-peek (ys &optional (n 0))
  (let ((i (+ (ys-pos ys) n)))
    (when (< i (ys-len ys))
      (char (ys-text ys) i))))

(defun ys-next (ys)
  (when (< (ys-pos ys) (ys-len ys))
    (prog1 (char (ys-text ys) (ys-pos ys))
      (incf (ys-pos ys)))))

(defun ys-column (ys)
  (let ((text (ys-text ys))
        (pos (ys-pos ys)))
    (loop for i from (1- pos) downto 0
          when (char= (char text i) #\Newline)
            return (- pos i 1)
          finally (return pos))))

(defun emit (ys kind &key (implicit t) flow-p anchor tag style value)
  (vector-push-extend
   (make-yaml-event :kind kind :implicit implicit :flow-p flow-p
                    :anchor (and anchor (plusp (length anchor)) anchor)
                    :tag tag :style (or style :plain) :value value)
   (ys-events ys)))

(defun space-p (c)
  (eql c #\Space))

(defun blank-p (c)
  (or (eql c #\Space) (eql c #\Tab)))

(defun break-p (c)
  (or (eql c #\Newline) (eql c #\Return)))

(defun skip-spaces (ys)
  (loop while (space-p (ys-peek ys)) do (ys-next ys)))

(defun skip-blanks (ys)
  (loop while (blank-p (ys-peek ys)) do (ys-next ys)))

(defun skip-comment (ys)
  (when (eql (ys-peek ys) #\#)
    (loop until (or (ys-eof-p ys) (break-p (ys-peek ys)))
          do (ys-next ys))))

(defun skip-break (ys)
  (cond
    ((eql (ys-peek ys) #\Return)
     (ys-next ys)
     (when (eql (ys-peek ys) #\Newline)
       (ys-next ys))
     t)
    ((eql (ys-peek ys) #\Newline)
     (ys-next ys)
     t)
    (t nil)))

(defun skip-ws-breaks (ys)
  "Skip spaces, tabs, comments, and line breaks."
  (loop
    (skip-blanks ys)
    (cond
      ((eql (ys-peek ys) #\#) (skip-comment ys))
      ((skip-break ys))
      (t (return)))))

(defun at-bol-p (ys)
  (or (zerop (ys-pos ys))
      (let ((c (char (ys-text ys) (1- (ys-pos ys)))))
        (or (char= c #\Newline) (char= c #\Return)))))

(defun at-marker-p (ys marker)
  (and (at-bol-p ys)
       (let ((n (length marker)))
         (loop for i below n
               unless (eql (ys-peek ys i) (char marker i))
                 return nil
               finally (let ((c (ys-peek ys n)))
                         (return (or (null c) (blank-p c) (break-p c)
                                     (eql c #\#))))))))

(defun consume-marker (ys marker)
  (dotimes (i (length marker))
    (ys-next ys))
  (skip-blanks ys)
  (skip-comment ys))

(defun fail-parse (ys fmt &rest args)
  (error 'yaml-parse-error
         :message (format nil "~A (pos ~D)"
                          (apply #'format nil fmt args)
                          (ys-pos ys))))

(defun skip-bom (ys)
  (when (eql (ys-peek ys) #\ufeff)
    (ys-next ys)))

(defun parse-hex (ys n)
  (let ((acc 0))
    (dotimes (i n acc)
      (let ((c (ys-next ys)))
        (unless (hex-digit-p c)
          (fail-parse ys "bad hex escape"))
        (setf acc (+ (* acc 16)
                     (digit-char-p c 16)))))))

(defun percent-decode (s)
  (with-output-to-string (o)
    (loop with i = 0
          with n = (length s)
          while (< i n)
          do (let ((c (char s i)))
               (if (and (char= c #\%) (<= (+ i 3) n)
                        (hex-digit-p (char s (1+ i)))
                        (hex-digit-p (char s (+ i 2))))
                   (progn
                     (write-char (code-char
                                  (+ (* 16 (digit-char-p (char s (1+ i)) 16))
                                     (digit-char-p (char s (+ i 2)) 16)))
                                 o)
                     (incf i 3))
                   (progn
                     (write-char c o)
                     (incf i)))))))

(defun resolve-tag (ys raw)
  "Resolve a tag token (!foo, !!str, !e!name, !<uri>, !) against handles."
  (cond
    ((or (null raw) (string= raw "")) nil)
    ((and (>= (length raw) 2)
          (char= (char raw 0) #\<)
          (char= (char raw (1- (length raw))) #\>))
     (subseq raw 1 (1- (length raw))))
    ((string= raw "!") "!")
    ((and (>= (length raw) 2) (char= (char raw 0) #\!)
          (char= (char raw 1) #\!))
     (concatenate 'string (gethash "!!" (ys-tag-handles ys) "tag:yaml.org,2002:")
                  (percent-decode (subseq raw 2))))
    ((char= (char raw 0) #\!)
     (let* ((rest (subseq raw 1))
            (bang (position #\! rest)))
       (if bang
           (let* ((handle (concatenate 'string "!" (subseq rest 0 (1+ bang))))
                  (suffix (percent-decode (subseq rest (1+ bang))))
                  (prefix (gethash handle (ys-tag-handles ys))))
             (unless prefix
               (fail-parse ys "undefined tag handle ~A" handle))
             (concatenate 'string prefix suffix))
           (let ((prefix (gethash "!" (ys-tag-handles ys) "!")))
             (concatenate 'string prefix (percent-decode rest))))))
    (t raw)))

(defun ns-word-char-p (c)
  (and c (or (alphanumericp c) (char= c #\-))))

(defun parse-tag-token (ys)
  "Consume a !tag after the first ! has been eaten. Returns raw including !."
  (cond
    ((eql (ys-peek ys) #\<)
     (ys-next ys)
     (let ((uri (with-output-to-string (o)
                  (loop for c = (ys-peek ys)
                        until (or (null c) (char= c #\>))
                        do (write-char (ys-next ys) o)))))
       (unless (eql (ys-next ys) #\>)
         (fail-parse ys "unterminated verbatim tag"))
       (concatenate 'string "<" uri ">")))
    ((eql (ys-peek ys) #\!)
     (ys-next ys)
     (let ((name (with-output-to-string (o)
                   (loop for c = (ys-peek ys)
                         while (and c (not (blank-p c)) (not (break-p c))
                                    (not (member c '(#\[ #\] #\{ #\} #\,))))
                         do (write-char (ys-next ys) o)))))
       (concatenate 'string "!!" name)))
    (t
     (let ((name (with-output-to-string (o)
                   (loop for c = (ys-peek ys)
                         while (and c (not (blank-p c)) (not (break-p c))
                                    (not (member c '(#\[ #\] #\{ #\} #\,))))
                         do (write-char (ys-next ys) o)))))
       (concatenate 'string "!" name)))))

(defun parse-anchor-name (ys)
  (let ((name (with-output-to-string (o)
                (loop for c = (ys-peek ys)
                      while (and c (not (blank-p c)) (not (break-p c))
                                 (not (member c '(#\[ #\] #\{ #\} #\, #\:))))
                      do (write-char (ys-next ys) o)))))
    (when (zerop (length name))
      (fail-parse ys "empty anchor/alias"))
    name))

(defun parse-properties (ys)
  "Optional &anchor / !tag (either order, at most one of each).
   Returns (values anchor tag)."
  (let ((anchor nil)
        (tag nil))
    (loop
      (skip-blanks ys)
      (cond
        ((eql (ys-peek ys) #\&)
         (when anchor
           (fail-parse ys "duplicate anchor"))
         (ys-next ys)
         (setf anchor (parse-anchor-name ys)))
        ((eql (ys-peek ys) #\!)
         (when tag
           (fail-parse ys "duplicate tag"))
         (ys-next ys)
         (setf tag (resolve-tag ys (parse-tag-token ys))))
        (t (return))))
    (values anchor tag)))

(defun skip-to-node-content (ys indent)
  "After properties, skip comment/break and require indent > parent when broken."
  (skip-blanks ys)
  (skip-comment ys)
  (when (or (break-p (ys-peek ys)) (ys-eof-p ys))
    (skip-break ys)
    (loop
      (skip-spaces ys)
      (cond
        ((eql (ys-peek ys) #\#)
         (skip-comment ys)
         (skip-break ys))
        ((break-p (ys-peek ys))
         (skip-break ys))
        (t (return))))
    (when (and (not (ys-eof-p ys))
               (<= (ys-column ys) indent)
               (not (at-marker-p ys "---"))
               (not (at-marker-p ys "...")))
      ;; empty node — caller sees eof / same-or-less indent
      nil)))

(defun dq-unescape (ys)
  (let ((e (ys-next ys)))
    (when (null e)
      (fail-parse ys "unterminated escape"))
    (cond
      ((char= e #\0) #\Nul)
      ((char= e #\a) #\Bel)
      ((char= e #\b) #\Backspace)
      ((char= e #\t) #\Tab)
      ((char= e #\n) #\Newline)
      ((char= e #\v) #\Vt)
      ((char= e #\f) #\Page)
      ((char= e #\r) #\Return)
      ((char= e #\e) #\Esc)
      ((char= e #\") #\")
      ((char= e #\/) #\/)
      ((char= e #\\) #\\)
      ((char= e #\N) (code-char #x85))
      ((char= e #\_) (code-char #xa0))
      ((char= e #\L) (code-char #x2028))
      ((char= e #\P) (code-char #x2029))
      ((char= e #\x) (code-char (parse-hex ys 2)))
      ((char= e #\u) (code-char (parse-hex ys 4)))
      ((char= e #\U) (code-char (parse-hex ys 8)))
      ((or (char= e #\Newline) (char= e #\Return))
       (when (and (char= e #\Return) (eql (ys-peek ys) #\Newline))
         (ys-next ys))
       :escaped-break)
      (t (fail-parse ys "unknown escape \\~A" e)))))

(defun fold-flow-break (ys chars indent)
  "s-flow-folded. Mutates CHARSvia push (reversed). Returns updated chars."
  (loop while (and chars (blank-p (car chars)))
        do (pop chars))
  (skip-break ys)
  (let ((empty 0))
    (loop
      (let ((col (ys-column ys)))
        (loop while (space-p (ys-peek ys))
              do (ys-next ys))
        (cond
          ((and (eql (ys-peek ys) #\Tab) (<= col indent))
           (fail-parse ys "tab used as indentation"))
          ((break-p (ys-peek ys))
           (skip-break ys)
           (incf empty))
          (t (return)))))
    (loop while (blank-p (ys-peek ys))
          do (ys-next ys))
    (if (plusp empty)
        (dotimes (i empty chars)
          (push #\Newline chars))
        (progn (push #\Space chars) chars))))

(defun parse-double-quoted (ys &key (indent -1))
  (unless (eql (ys-next ys) #\")
    (fail-parse ys "expected \""))
  (let ((chars '()))
    (loop
      (let ((c (ys-peek ys)))
        (cond
          ((null c) (fail-parse ys "unterminated double-quoted string"))
          ((char= c #\")
           (ys-next ys)
           (return (coerce (nreverse chars) 'string)))
          ((char= c #\\)
           (ys-next ys)
           (let ((x (dq-unescape ys)))
             (if (eq x :escaped-break)
                 (progn
                   (loop while (blank-p (ys-peek ys))
                         do (ys-next ys)))
                 (push x chars))))
          ((break-p c)
           (setf chars (fold-flow-break ys chars indent)))
          (t
           (push (ys-next ys) chars)))))))

(defun parse-single-quoted (ys &key (indent -1))
  (unless (eql (ys-next ys) #\')
    (fail-parse ys "expected '"))
  (let ((chars '()))
    (loop
      (let ((c (ys-peek ys)))
        (cond
          ((null c) (fail-parse ys "unterminated single-quoted string"))
          ((char= c #\')
           (ys-next ys)
           (if (eql (ys-peek ys) #\')
               (push (ys-next ys) chars)
               (return (coerce (nreverse chars) 'string))))
          ((break-p c)
           (setf chars (fold-flow-break ys chars indent)))
          (t
           (push (ys-next ys) chars)))))))

(defun plain-stop-p (c flow)
  (or (null c)
      (break-p c)
      (and flow (member c '(#\, #\[ #\] #\{ #\})))))

(defun colon-ends-plain-p (ys flow)
  (let ((n (ys-peek ys 1)))
    (or (null n) (blank-p n) (break-p n)
        (and flow (member n '(#\, #\] #\}))))))

(defun parse-plain (ys &key flow (indent -1))
  (let ((chars '()))
    (loop
      (let ((c (ys-peek ys)))
        (cond
          ((and (break-p c) (not flow))
           (let ((saved (ys-pos ys))
                 (saved-chars chars))
             (loop while (and chars (blank-p (car chars)))
                   do (pop chars))
             (skip-break ys)
             (let ((empty 0)
                   (ok t))
               (loop
                 (skip-spaces ys)
                 (cond
                   ((break-p (ys-peek ys))
                    (skip-break ys)
                    (incf empty))
                   (t (return))))
               (let ((col (ys-column ys))
                     (n (ys-peek ys)))
                 (when (or (null n)
                           (<= col indent)
                           (at-marker-p ys "---")
                           (at-marker-p ys "...")
                           (eql n #\#)
                           (and (eql n #\-)
                                (let ((x (ys-peek ys 1)))
                                  (or (null x) (blank-p x) (break-p x))))
                           (and (eql n #\?)
                                (let ((x (ys-peek ys 1)))
                                  (or (null x) (blank-p x) (break-p x))))
                           (and (eql n #\:)
                                (let ((x (ys-peek ys 1)))
                                  (or (null x) (blank-p x) (break-p x)))))
                   (setf (ys-pos ys) saved
                         chars saved-chars
                         ok nil)))
               (if ok
                   (if (plusp empty)
                       (dotimes (i empty) (push #\Newline chars))
                       (push #\Space chars))
                   (return)))))
          ((plain-stop-p c flow)
           (return))
          ((and (eql c #\:) (colon-ends-plain-p ys flow))
           (return))
          ((and (blank-p c) (eql (ys-peek ys 1) #\#))
           (return))
          ((eql c #\#)
           (if (and chars (blank-p (car chars)))
               (return)
               (push (ys-next ys) chars)))
          (t
           (push (ys-next ys) chars)))))
    (loop while (and chars (blank-p (car chars)))
          do (pop chars))
    (coerce (nreverse chars) 'string)))

(defun parse-block-scalar (ys &key (indent -1))
  (let ((kind (ys-next ys))
        (chomp :clip)
        (explicit-indent nil))
    (unless (or (char= kind #\|) (char= kind #\>))
      (fail-parse ys "expected block scalar"))
    (loop
      (let ((c (ys-peek ys)))
        (cond
          ((eql c #\-) (ys-next ys) (setf chomp :strip))
          ((eql c #\+) (ys-next ys) (setf chomp :keep))
          ((and c (char<= #\1 c #\9))
           (setf explicit-indent (digit-char-p (ys-next ys))))
          (t (return)))))
    (skip-blanks ys)
    (skip-comment ys)
    (unless (or (ys-eof-p ys) (break-p (ys-peek ys)))
      (fail-parse ys "trailing junk after block scalar header"))
    (skip-break ys)
    (let* ((parent (max indent 0))
           (content-indent (and explicit-indent (+ parent explicit-indent)))
           (lines '()))
      (loop
        (when (ys-eof-p ys)
          (return))
        (let ((col 0))
          (loop while (space-p (ys-peek ys))
                do (ys-next ys) (incf col))
          (cond
            ((and (eql (ys-peek ys) #\Tab) (or (null content-indent)
                                               (< col content-indent)))
             (fail-parse ys "tab used as indentation"))
            ((or (ys-eof-p ys) (break-p (ys-peek ys)))
             (push "" lines)
             (skip-break ys))
            ((and content-indent (< col content-indent)
                  (eql (ys-peek ys) #\#))
             (return))
            (t
             (unless content-indent
               (when (<= col parent)
                 (decf (ys-pos ys) col)
                 (return))
               (setf content-indent col))
             (when (< col content-indent)
               (decf (ys-pos ys) col)
               (return))
             (let ((extra (- col content-indent)))
               (push (concatenate 'string
                                  (make-string extra :initial-element #\Space)
                                  (with-output-to-string (o)
                                    (loop until (or (ys-eof-p ys)
                                                    (break-p (ys-peek ys)))
                                          do (write-char (ys-next ys) o))))
                     lines)
               (skip-break ys))))))
      (setf lines (nreverse lines))
      ;; drop trailing empty lines for clip/strip measurement; apply chomp after join
      (let ((text (if (char= kind #\|)
                      (%join-literal lines)
                      (%join-folded lines))))
        (values (%apply-chomp text chomp)
                (if (char= kind #\|) :literal :folded))))))

(defun %join-literal (lines)
  (if (null lines)
      ""
      (format nil "~{~A~^~%~}" lines)))

(defun %join-folded (lines)
  (with-output-to-string (out)
    (let ((prev-empty t)
          (first t))
      (dolist (line lines)
        (let ((empty (zerop (length line)))
              (more (and (plusp (length line))
                         (blank-p (char line 0)))))
          (cond
            (empty
             (write-char #\Newline out)
             (setf prev-empty t))
            (more
             (unless first
               (write-char #\Newline out))
             (write-string line out)
             (setf prev-empty nil first nil))
            (t
             (unless first
               (write-char (if prev-empty #\Newline #\Space) out))
             (write-string line out)
             (setf prev-empty nil first nil))))))))

(defun %apply-chomp (text chomp)
  (ecase chomp
    (:keep
     (if (and (plusp (length text))
              (not (char= (char text (1- (length text))) #\Newline)))
         (concatenate 'string text (string #\Newline))
         text))
    (:strip
     (let ((end (length text)))
       (loop while (and (plusp end) (char= (char text (1- end)) #\Newline))
             do (decf end))
       (subseq text 0 end)))
    (:clip
     (let ((stripped (%apply-chomp text :strip)))
       (if (plusp (length text))
           (concatenate 'string stripped (string #\Newline))
           stripped)))))

(defun looks-like-block-seq-p (ys)
  (and (eql (ys-peek ys) #\-)
       (let ((n (ys-peek ys 1)))
         (or (null n) (blank-p n) (break-p n) (eql n #\#)))))

(defun looks-like-explicit-key-p (ys)
  (and (eql (ys-peek ys) #\?)
       (let ((n (ys-peek ys 1)))
         (or (null n) (blank-p n) (break-p n) (eql n #\#)))))

(defun looks-like-block-map-p (ys)
  (or (looks-like-explicit-key-p ys)
      (let ((saved (ys-pos ys)))
        (unwind-protect
             (progn
               (cond
                 ((eql (ys-peek ys) #\")
                  (ignore-errors (parse-double-quoted ys)))
                 ((eql (ys-peek ys) #\')
                  (ignore-errors (parse-single-quoted ys)))
                 ((eql (ys-peek ys) #\*)
                  (ys-next ys)
                  (ignore-errors (parse-anchor-name ys)))
                 ((or (eql (ys-peek ys) #\&) (eql (ys-peek ys) #\!))
                  (parse-properties ys)
                  (skip-blanks ys)
                  (return-from looks-like-block-map-p
                    (progn (setf (ys-pos ys) saved)
                           (looks-like-block-map-p ys))))
                 (t
                  (loop
                    (let ((c (ys-peek ys)))
                      (cond
                        ((or (null c) (break-p c) (eql c #\#))
                         (return))
                        ((and (eql c #\:) (colon-ends-plain-p ys nil))
                         (return))
                        (t (ys-next ys)))))))
               (skip-blanks ys)
               (eql (ys-peek ys) #\:))
          (setf (ys-pos ys) saved)))))

(defun emit-scalar (ys value &key anchor tag style)
  (emit ys :scalar :anchor anchor :tag tag :style (or style :plain)
        :value (or value "")))

(defun parse-flow-seq (ys &key anchor tag)
  (unless (eql (ys-next ys) #\[)
    (fail-parse ys "expected ["))
  (emit ys :sequence-start :flow-p t :anchor anchor :tag tag)
  (skip-ws-breaks ys)
  (loop
    (skip-ws-breaks ys)
    (when (eql (ys-peek ys) #\])
      (ys-next ys)
      (emit ys :sequence-end)
      (return))
    (parse-node ys :flow t :indent -1)
    (skip-ws-breaks ys)
    (cond
      ((eql (ys-peek ys) #\])
       (ys-next ys)
       (emit ys :sequence-end)
       (return))
      ((eql (ys-peek ys) #\,)
       (ys-next ys)
       (skip-ws-breaks ys)
       (when (eql (ys-peek ys) #\])
         (ys-next ys)
         (emit ys :sequence-end)
         (return)))
      (t (fail-parse ys "expected , or ] in flow sequence")))))

(defun parse-flow-map (ys &key anchor tag)
  (unless (eql (ys-next ys) #\{)
    (fail-parse ys "expected {"))
  (emit ys :mapping-start :flow-p t :anchor anchor :tag tag)
  (skip-ws-breaks ys)
  (loop
    (skip-ws-breaks ys)
    (when (eql (ys-peek ys) #\})
      (ys-next ys)
      (emit ys :mapping-end)
      (return))
    (if (looks-like-explicit-key-p ys)
        (progn
          (ys-next ys)
          (skip-ws-breaks ys)
          (parse-node ys :flow t :indent -1 :key :explicit)
          (skip-ws-breaks ys)
          (if (eql (ys-peek ys) #\:)
              (progn
                (ys-next ys)
                (skip-ws-breaks ys)
                (if (member (ys-peek ys) '(#\, #\}))
                    (emit-scalar ys "")
                    (parse-node ys :flow t :indent -1)))
              (emit-scalar ys "")))
        (progn
          (parse-node ys :flow t :indent -1 :key :implicit)
          (skip-ws-breaks ys)
          (cond
            ((eql (ys-peek ys) #\:)
             (ys-next ys)
             (skip-ws-breaks ys)
             (if (member (ys-peek ys) '(#\, #\}))
                 (emit-scalar ys "")
                 (parse-node ys :flow t :indent -1)))
            ((member (ys-peek ys) '(#\, #\}))
             (emit-scalar ys ""))
            (t (fail-parse ys "expected : , or } in flow mapping")))))
    (skip-ws-breaks ys)
    (cond
      ((eql (ys-peek ys) #\})
       (ys-next ys)
       (emit ys :mapping-end)
       (return))
      ((eql (ys-peek ys) #\,)
       (ys-next ys))
      (t (fail-parse ys "expected , or } in flow mapping")))))

(defun parse-block-seq (ys &key anchor tag)
  (let ((indent (ys-column ys)))
    (emit ys :sequence-start :anchor anchor :tag tag)
    (loop
      (skip-spaces ys)
      (when (or (ys-eof-p ys)
                (at-marker-p ys "---")
                (at-marker-p ys "..."))
        (return))
      (let ((col (ys-column ys)))
        (cond
          ((< col indent)
           (return))
          ((> col indent)
           (fail-parse ys "bad sequence indent"))
          ((not (looks-like-block-seq-p ys))
           (return))
          (t
           (ys-next ys)                 ; -
           (cond
             ((or (ys-eof-p ys) (break-p (ys-peek ys)) (eql (ys-peek ys) #\#))
              (skip-comment ys)
              (skip-break ys)
              (skip-ws-breaks ys)
              (if (and (not (ys-eof-p ys))
                       (not (at-marker-p ys "---"))
                       (not (at-marker-p ys "..."))
                       (> (ys-column ys) indent))
                  (parse-node ys :indent indent)
                  (emit-scalar ys "")))
             ((blank-p (ys-peek ys))
              (skip-blanks ys)
              (if (or (ys-eof-p ys) (break-p (ys-peek ys)) (eql (ys-peek ys) #\#))
                  (progn
                    (skip-comment ys)
                    (skip-break ys)
                    (skip-ws-breaks ys)
                    (if (and (not (ys-eof-p ys))
                             (> (ys-column ys) indent)
                             (not (at-marker-p ys "---"))
                             (not (at-marker-p ys "...")))
                        (parse-node ys :indent indent)
                        (emit-scalar ys "")))
                  (parse-node ys :indent indent)))
             (t
              (decf (ys-pos ys))
              (return))))))
      (skip-ws-breaks ys))
    (emit ys :sequence-end)))

(defun parse-block-map (ys &key anchor tag)
  (let ((indent (ys-column ys)))
    (emit ys :mapping-start :anchor anchor :tag tag)
    (loop
      (skip-spaces ys)
      (when (or (ys-eof-p ys)
                (at-marker-p ys "---")
                (at-marker-p ys "..."))
        (return))
      (let ((col (ys-column ys)))
        (when (< col indent)
          (return))
        (when (looks-like-block-seq-p ys)
          (return))
        (when (eql (ys-peek ys) #\Tab)
          (fail-parse ys "tab used as indentation"))
        (unless (= col indent)
          (when (> col indent)
            (fail-parse ys "bad mapping indent"))
          (return))
        (cond
          ((looks-like-explicit-key-p ys)
           (ys-next ys)
           (skip-blanks ys)
           (skip-comment ys)
           (cond
             ((or (ys-eof-p ys) (break-p (ys-peek ys)))
              (skip-break ys)
              (skip-ws-breaks ys)
                  (if (and (not (ys-eof-p ys))
                       (> (ys-column ys) indent))
                  (parse-node ys :indent indent :key :explicit)
                  (emit-scalar ys "")))
             (t (parse-node ys :indent indent :key :explicit)))
           (skip-ws-breaks ys)
           (skip-spaces ys)
           (if (and (= (ys-column ys) indent) (eql (ys-peek ys) #\:))
               (progn
                 (ys-next ys)
                 (skip-blanks ys)
                 (skip-comment ys)
                 (cond
                   ((or (ys-eof-p ys) (break-p (ys-peek ys)))
                    (skip-break ys)
                    (skip-ws-breaks ys)
                    (if (and (not (ys-eof-p ys))
                             (not (at-marker-p ys "---"))
                             (not (at-marker-p ys "..."))
                             (> (ys-column ys) indent))
                        (parse-node ys :indent indent)
                        (emit-scalar ys "")))
                   (t (parse-node ys :indent indent))))
               (emit-scalar ys "")))
          (t
           (unless (looks-like-block-map-p ys)
             (return))
           (parse-node ys :indent indent :key :implicit)
           (skip-blanks ys)
           (unless (eql (ys-peek ys) #\:)
             (fail-parse ys "expected : after mapping key"))
           (ys-next ys)
           (skip-blanks ys)
           (skip-comment ys)
           (cond
             ((or (ys-eof-p ys) (break-p (ys-peek ys)))
              (skip-break ys)
              (skip-ws-breaks ys)
              (if (and (not (ys-eof-p ys))
                       (not (at-marker-p ys "---"))
                       (not (at-marker-p ys "..."))
                       (> (ys-column ys) indent))
                  (parse-node ys :indent indent)
                  (emit-scalar ys "")))
             (t (parse-node ys :indent indent))))))
      (skip-ws-breaks ys))
    (emit ys :mapping-end)))

(defun parse-node (ys &key flow (indent -1) key)
  "KEY :implicit — single-line implicit mapping key (no block collection).
   KEY :explicit — `?` key; block collections allowed."
  (when (eql (ys-peek ys) #\*)
    (ys-next ys)
    (let ((name (parse-anchor-name ys)))
      (emit ys :alias :value name)
      (return-from parse-node)))
  (multiple-value-bind (anchor tag)
      (parse-properties ys)
    (skip-to-node-content ys indent)
    (let ((c (ys-peek ys))
          (allow-block (not (eq key :implicit))))
      (cond
        ((or (null c)
             (and (not flow)
                  (or (at-marker-p ys "---")
                      (at-marker-p ys "...")
                      (< (ys-column ys) indent))))
         (emit-scalar ys "" :anchor anchor :tag tag))
        ((eql c #\{)
         (parse-flow-map ys :anchor anchor :tag tag))
        ((eql c #\[)
         (parse-flow-seq ys :anchor anchor :tag tag))
        ((or (eql c #\|) (eql c #\>))
         (multiple-value-bind (text style)
             (parse-block-scalar ys :indent indent)
           (emit-scalar ys text :anchor anchor :tag tag :style style)))
        ((eql c #\")
         (emit-scalar ys (parse-double-quoted ys :indent indent)
                      :anchor anchor :tag tag :style :double))
        ((eql c #\')
         (emit-scalar ys (parse-single-quoted ys :indent indent)
                      :anchor anchor :tag tag :style :single))
        ((and (not flow) allow-block (looks-like-block-seq-p ys))
         (parse-block-seq ys :anchor anchor :tag tag))
        ((and (not flow) allow-block (looks-like-block-map-p ys))
         (parse-block-map ys :anchor anchor :tag tag))
        (t
         (let ((plain (parse-plain ys :flow flow :indent indent)))
           (emit-scalar ys plain :anchor anchor :tag tag :style :plain)))))))

(defun parse-directive-line (ys)
  "Consume a %directive at column 0. %TAG updates handles; others ignored."
  (unless (eql (ys-next ys) #\%)
    (fail-parse ys "expected %"))
  (let ((name (with-output-to-string (o)
                (loop for c = (ys-peek ys)
                      while (and c (not (blank-p c)) (not (break-p c)))
                      do (write-char (ys-next ys) o)))))
    (skip-blanks ys)
    (cond
      ((string= name "TAG")
       (let ((handle (with-output-to-string (o)
                       (loop for c = (ys-peek ys)
                             while (and c (not (blank-p c)) (not (break-p c)))
                             do (write-char (ys-next ys) o)))))
         (skip-blanks ys)
         (let ((prefix (with-output-to-string (o)
                         (loop for c = (ys-peek ys)
                               while (and c (not (blank-p c)) (not (break-p c))
                                          (not (eql c #\#)))
                               do (write-char (ys-next ys) o)))))
           (when (or (zerop (length handle)) (zerop (length prefix)))
             (fail-parse ys "bad %TAG"))
           (setf (gethash handle (ys-tag-handles ys)) prefix))))
      ((string= name "YAML")
       (loop for c = (ys-peek ys)
             while (and c (not (break-p c)) (not (eql c #\#)))
             do (ys-next ys)))
      (t
       (loop for c = (ys-peek ys)
             while (and c (not (break-p c)))
             do (ys-next ys))))
    (skip-blanks ys)
    (skip-comment ys)
    (unless (or (ys-eof-p ys) (break-p (ys-peek ys)))
      (fail-parse ys "trailing junk after directive"))
    (skip-break ys)))

(defun parse-directives (ys)
  (let ((any nil))
    (loop
      (skip-spaces ys)
      (cond
        ((and (at-bol-p ys) (eql (ys-peek ys) #\%))
         (setf any t)
         (parse-directive-line ys))
        ((eql (ys-peek ys) #\#)
         (skip-comment ys)
         (skip-break ys))
        ((break-p (ys-peek ys))
         (skip-break ys))
        (t (return))))
    any))

(defun parse-document (ys)
  (reset-tag-handles ys)
  (let ((had-directives (parse-directives ys))
        (explicit-start nil)
        (explicit-end nil))
    (skip-ws-breaks ys)
    (when (at-marker-p ys "---")
      (consume-marker ys "---")
      (setf explicit-start t)
      (skip-ws-breaks ys))
    (when (and (not explicit-start)
               (not had-directives)
               (or (ys-eof-p ys)
                   (at-marker-p ys "...")))
      (when (at-marker-p ys "...")
        (consume-marker ys "...")
        (skip-ws-breaks ys))
      (return-from parse-document nil))
    (emit ys :document-start :implicit (not explicit-start))
    (cond
      ((or (ys-eof-p ys)
           (at-marker-p ys "---")
           (at-marker-p ys "..."))
       (emit-scalar ys ""))
      (t
       (parse-node ys :indent -1)
       (skip-ws-breaks ys)
       (when (and (not (ys-eof-p ys))
                  (not (at-marker-p ys "---"))
                  (not (at-marker-p ys "..."))
                  (eql (ys-peek ys) #\%)
                  (at-bol-p ys))
         (fail-parse ys "directives require a document end marker"))))
    (skip-ws-breaks ys)
    (when (at-marker-p ys "...")
      (consume-marker ys "...")
      (setf explicit-end t)
      (skip-ws-breaks ys))
    (emit ys :document-end :implicit (not explicit-end))
    t))

(defun parse-events-from-string (text)
  (let ((ys (make-ys (or text ""))))
    (skip-bom ys)
    (reset-tag-handles ys)
    (emit ys :stream-start)
    (skip-ws-breaks ys)
    (loop
      (skip-ws-breaks ys)
      (when (ys-eof-p ys)
        (return))
      (unless (parse-document ys)
        (when (ys-eof-p ys)
          (return))
        (unless (or (at-marker-p ys "---")
                    (at-marker-p ys "...")
                    (eql (ys-peek ys) #\%))
          (return))))
    (emit ys :stream-end)
    (coerce (ys-events ys) 'list)))

(defun parse-yaml (text &key all)
  (compose-events (parse-events-from-string text) :all all))
